import { test } from 'node:test';
import assert from 'node:assert/strict';
function expect(actual: any) { return {toBe:(v:any)=>assert.strictEqual(actual,v),toEqual:(v:any)=>assert.deepStrictEqual(actual,v),toContain:(v:any)=>assert.ok(actual.includes(v)),toBeNull:()=>assert.strictEqual(actual,null),not:{toBe:(v:any)=>assert.notStrictEqual(actual,v),toContain:(v:any)=>assert.ok(!actual.includes(v))}}; }
import { createServer } from 'node:http';
import { createChatServer } from '../services/hermes-chat/server.mjs';
async function fixture(handler: any = (_q: any, r: any) => r.end('data: {"choices":[{"delta":{"content":"你好"}}]}\n\ndata: [DONE]\n\n'), options = {}) {
 const upstream = createServer(handler); await new Promise<void>(r => upstream.listen(0, '127.0.0.1', r));
 const bridge = createChatServer({ apiKey:'private-key', apiUrl:`http://127.0.0.1:${(upstream.address() as any).port}`, ...options });
 await new Promise<void>(r => bridge.listen(0,'127.0.0.1',r));
 const url = `http://127.0.0.1:${(bridge.address() as any).port}/chat-api`;
 return { post:(body: any = {messages:[{role:'user',content:'Hello'}]}, headers = {}, signal?: AbortSignal) => fetch(url,{method:'POST',body:JSON.stringify(body),headers:{'Content-Type':'application/json',...headers},signal}), url, close:()=>{bridge.closeAllConnections(); bridge.close(); upstream.closeAllConnections();upstream.close();} };
}
test('validates roles, sequence, overrides and size without upstream calls', async()=> {
 let calls=0; const f=await fixture((_q:any,r:any)=>{calls++;r.end()});
 try { for(const body of [{messages:[{role:'system',content:'x'}]}, {messages:[{role:'tool',content:'x'}]}, {messages:[{role:'assistant',content:'x'}]}, {messages:[{role:'user',content:'x'},{role:'user',content:'y'}]}, {messages:[{role:'user',content:'x'}],model:'evil'}, {messages:[{role:'user',content:'x'.repeat(4001)}]}, {messages:Array.from({length:25},(_,i)=>({role:i%2?'assistant':'user',content:'x'}))}, {messages:Array.from({length:5},(_,i)=>({role:i%2?'assistant':'user',content:'x'.repeat(4000)}))}, {messages:[{role:'user',content:' '.repeat(33000)}]}]) expect([400,413]).toContain((await f.post(body,{'X-Real-IP':String(Math.random())})).status); expect(calls).toBe(0); } finally {f.close();}
});
test('requires allowed Origin, restricts paths and methods, returns safe health',async()=>{const f=await fixture();try {expect((await f.post(undefined,{Origin:'https://evil.com'})).status).toBe(403);expect((await fetch(f.url)).status).toBe(405);expect((await fetch(f.url+'/sessions')).status).toBe(404);expect(await (await fetch(f.url+'/health')).json()).toEqual({ok:true});expect((await f.post(undefined,{Origin:'https://siyuanxue.com'})).status).toBe(200);}finally{f.close()}});
test('sanitizes byte-split SSE and uses fresh private upstream sessions and fixed model',async()=>{
 const requests:any[]=[];const f=await fixture(async(q:any,r:any)=>{let body='';for await(const b of q)body+=b;requests.push({body:JSON.parse(body),auth:q.headers.authorization}); r.setHeader('X-Secret','private-key');const wire=Buffer.from('event: message\ndata: {"id":"secret-session","choices":[{"delta":{"reasoning":"secret-reason","content":"你好"}}]}\n\ndata: [DONE]\n\n');for(const byte of wire){r.write(Buffer.from([byte]));await new Promise(r=>setTimeout(r,1));}r.end();});
 try {for(let i=0;i<2;i++){const response=await f.post();expect(response.headers.get('x-secret')).toBeNull();expect(await response.text()).toBe('data: {"choices":[{"delta":{"content":"你好"}}]}\n\ndata: [DONE]\n\n');}expect(requests[0].body.model).toBe('hermes');expect(requests[0].body.stream).toBe(true);expect(requests[0].body.session_id).not.toBe(requests[1].body.session_id);expect(requests[0].auth).toBe('Bearer private-key');}finally{f.close()}
});
test('upstream errors and truncated streams give safe errors without DONE',async()=>{for(const wire of ['data: {"error":"private-key stack"}\n\n','data: {"choices":[{"delta":{"content":"partial"}}]}\n\n']){const f=await fixture((_q:any,r:any)=>r.end(wire));try{const text=await(await f.post()).text();expect(text).toContain('stream_error');expect(text).not.toContain('private-key');expect(text).not.toContain('[DONE]');}finally{f.close()}}});
test('enforces rolling IP rate limits',async()=>{const f=await fixture();try{for(let i=0;i<6;i++)expect((await(await f.post()).text())).toContain('[DONE]');expect((await f.post()).status).toBe(429);}finally{f.close()}});
test('enforces per-IP and global concurrency; disconnect releases upstream',async()=>{let disconnected=0;const f=await fixture((_q:any,r:any)=>{r.on('close',()=>disconnected++);r.write('data: {"choices":[{"delta":{"content":"start"}}]}\n\n')});const controllers:AbortController[]=[];try{for(const ip of ['1','1','2','2']){const c=new AbortController();controllers.push(c);expect((await f.post(undefined,{'X-Real-IP':ip},c.signal)).status).toBe(200);}expect((await f.post(undefined,{'X-Real-IP':'1'})).status).toBe(429);expect((await f.post(undefined,{'X-Real-IP':'3'})).status).toBe(429);controllers.forEach(c=>c.abort());await new Promise(r=>setTimeout(r,80));expect(disconnected).toBe(4);}finally{controllers.forEach(c=>c.abort());f.close()}});
test('timeout aborts upstream and returns safe failure',async()=>{let closed=false;const f=await fixture((_q:any,r:any)=>{r.on('close',()=>closed=true)}, {timeoutMs:30});try{const r=await f.post();expect(r.status).toBe(502);expect(await r.text()).not.toContain('private-key');await new Promise(r=>setTimeout(r,30));expect(closed).toBe(true);}finally{f.close()}});
