server {
	listen 80;
	listen [::]:80;
	server_name xuesiyuan.com.cn www.xuesiyuan.com.cn;

	location ^~ /.well-known/acme-challenge/ {
		root /var/lib/letsencrypt;
		default_type text/plain;
		try_files $uri =404;
	}

	location / {
		return 301 https://siyuanxue.com$request_uri;
	}
}

server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	server_name xuesiyuan.com.cn www.xuesiyuan.com.cn;

	ssl_certificate /etc/letsencrypt/live/xuesiyuan.com.cn/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/xuesiyuan.com.cn/privkey.pem;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 10m;
	ssl_session_tickets off;

	return 301 https://siyuanxue.com$request_uri;
}
